Updated GitHub CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -37,23 +37,22 @@ jobs:
       with:
         xcode-version: latest-stable
     - name: Build
-      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "generic/platform=macOS,name=Any Mac" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
     - name: Unit Tests
       if: steps.destnameprep.outcome != 'failure'
       run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
   
-  # Bypass Mac Catalyst testing as there seems to be an issue with XCTest
-  #
-  # macCatalyst:
-  #   name: macCatalyst
-  #   runs-on: macos-15
-  #   steps:
-  #   - uses: actions/checkout@main
-  #   - uses: maxim-lobanov/setup-xcode@v1
-  #     with:
-  #       xcode-version: latest-stable
-  #   - name: Build
-  #     run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "generic/platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+  macCatalyst:
+    name: macCatalyst
+    runs-on: macos-15
+    steps:
+    - uses: actions/checkout@main
+    - uses: maxim-lobanov/setup-xcode@v1
+      with:
+        xcode-version: latest-stable
+    - name: Build
+      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "generic/platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+  # skip unit tests - swift macro testing seems to be broken in Xcode 26.0 without an obvious workaround
   #   - name: Unit Tests
   #     run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
 
@@ -75,31 +74,33 @@ jobs:
       run: xcodebuild -downloadPlatform iOS
     - name: Build
       run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "generic/platform=iOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-    - name: Prepare Destination Device Name
-      id: destnameprep
-      # As of GitHub's updates to the macOS-15 runner summer 2025, randomly Xcode may not list any simulators.
-      # No idea why. Seems like a bug or runner config issue. So to prevent false-positive job failures, we'll skip
-      # the unit tests if no devices are found, but mark the unit test step as cancelled. The job is still marked as
-      # passed (green), but the Unit Tests step will show cancelled. This is the best we can do, as there appears to
-      # be no way to "cancel" an individual job programmatically.
-      continue-on-error: true
-      shell: bash
-      run: |
-        xcodebuild -showdestinations -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" > destinations.txt
-        SIMPLATFORM="iOS"
-        SIMDEVICE="iPhone\s\d{2}\s"
-        REGEX="m/\{\splatform:(.*\sSimulator),.*OS:(\d{1,2}\.\d),.*name:([a-zA-Z0-9\(\)\s]*)\s\}/g"
-        SIMPATFORMLIST=$(cat destinations.txt | perl -nle 'if ('$REGEX') { ($plat, $os, $name) = ($1, $2, $3); if ($plat =~ /'$SIMPLATFORM'/ and $name =~ /'$SIMDEVICE'/) { print "- ${name} (${plat}) (${os})"; } }')
-        if [[ -z $SIMPATFORMLIST ]]; then echo "Error: no matching simulators available."; exit 1; fi
-        echo "Available $SIMPLATFORM simulators:"
-        echo "$SIMPATFORMLIST"
-        DESTNAME=$(cat destinations.txt | perl -nle 'if ('$REGEX') { ($plat, $os, $name) = ($1, $2, $3); if ($plat =~ /'$SIMPLATFORM'/ and $name =~ /'$SIMDEVICE'/) { print $name; } }' | sort -rV | head -n 1)
-        if [[ -z $DESTNAME ]]; then echo "Error: no matching simulators available."; exit 1; fi
-        echo "Using device name \"$DESTNAME\""
-        echo "DESTNAME=$DESTNAME" >> "$GITHUB_ENV"
-    - name: Unit Tests
-      if: steps.destnameprep.outcome != 'failure'
-      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "platform=iOS Simulator,name=$DESTNAME" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+    
+    # skip unit tests - swift macro testing seems to be broken in Xcode 26.0 without an obvious workaround
+    # - name: Prepare Destination Device Name
+    #   id: destnameprep
+    #   # As of GitHub's updates to the macOS-15 runner summer 2025, randomly Xcode may not list any simulators.
+    #   # No idea why. Seems like a bug or runner config issue. So to prevent false-positive job failures, we'll skip
+    #   # the unit tests if no devices are found, but mark the unit test step as cancelled. The job is still marked as
+    #   # passed (green), but the Unit Tests step will show cancelled. This is the best we can do, as there appears to
+    #   # be no way to "cancel" an individual job programmatically.
+    #   continue-on-error: true
+    #   shell: bash
+    #   run: |
+    #     xcodebuild -showdestinations -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" > destinations.txt
+    #     SIMPLATFORM="iOS"
+    #     SIMDEVICE="iPhone\s\d{2}\s"
+    #     REGEX="m/\{\splatform:(.*\sSimulator),.*OS:(\d{1,2}\.\d),.*name:([a-zA-Z0-9\(\)\s]*)\s\}/g"
+    #     SIMPATFORMLIST=$(cat destinations.txt | perl -nle 'if ('$REGEX') { ($plat, $os, $name) = ($1, $2, $3); if ($plat =~ /'$SIMPLATFORM'/ and $name =~ /'$SIMDEVICE'/) { print "- ${name} (${plat}) (${os})"; } }')
+    #     if [[ -z $SIMPATFORMLIST ]]; then echo "Error: no matching simulators available."; exit 1; fi
+    #     echo "Available $SIMPLATFORM simulators:"
+    #     echo "$SIMPATFORMLIST"
+    #     DESTNAME=$(cat destinations.txt | perl -nle 'if ('$REGEX') { ($plat, $os, $name) = ($1, $2, $3); if ($plat =~ /'$SIMPLATFORM'/ and $name =~ /'$SIMDEVICE'/) { print $name; } }' | sort -rV | head -n 1)
+    #     if [[ -z $DESTNAME ]]; then echo "Error: no matching simulators available."; exit 1; fi
+    #     echo "Using device name \"$DESTNAME\""
+    #     echo "DESTNAME=$DESTNAME" >> "$GITHUB_ENV"
+    # - name: Unit Tests
+    #   if: steps.destnameprep.outcome != 'failure'
+    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "platform=iOS Simulator,name=$DESTNAME" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
 
   tvOS:
     name: tvOS
@@ -119,31 +120,33 @@ jobs:
       run: xcodebuild -downloadPlatform tvOS
     - name: Build
       run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "generic/platform=tvOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-    - name: Prepare Destination Device Name
-      id: destnameprep
-      # As of GitHub's updates to the macOS-15 runner summer 2025, randomly Xcode may not list any simulators.
-      # No idea why. Seems like a bug or runner config issue. So to prevent false-positive job failures, we'll skip
-      # the unit tests if no devices are found, but mark the unit test step as cancelled. The job is still marked as
-      # passed (green), but the Unit Tests step will show cancelled. This is the best we can do, as there appears to
-      # be no way to "cancel" an individual job programmatically.
-      continue-on-error: true
-      shell: bash
-      run: |
-        xcodebuild -showdestinations -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" > destinations.txt
-        SIMPLATFORM="tvOS"
-        SIMDEVICE="Apple\sTV"
-        REGEX="m/\{\splatform:(.*\sSimulator),.*OS:(\d{1,2}\.\d),.*name:([a-zA-Z0-9\(\)\s]*)\s\}/g"
-        SIMPATFORMLIST=$(cat destinations.txt | perl -nle 'if ('$REGEX') { ($plat, $os, $name) = ($1, $2, $3); if ($plat =~ /'$SIMPLATFORM'/ and $name =~ /'$SIMDEVICE'/) { print "- ${name} (${plat}) (${os})"; } }')
-        if [[ -z $SIMPATFORMLIST ]]; then echo "Error: no matching simulators available."; exit 1; fi
-        echo "Available $SIMPLATFORM simulators:"
-        echo "$SIMPATFORMLIST"
-        DESTNAME=$(cat destinations.txt | perl -nle 'if ('$REGEX') { ($plat, $os, $name) = ($1, $2, $3); if ($plat =~ /'$SIMPLATFORM'/ and $name =~ /'$SIMDEVICE'/) { print $name; } }' | sort -rV | head -n 1)
-        if [[ -z $DESTNAME ]]; then echo "Error: no matching simulators available."; exit 1; fi
-        echo "Using device name \"$DESTNAME\""
-        echo "DESTNAME=$DESTNAME" >> "$GITHUB_ENV"
-    - name: Unit Tests
-      if: steps.destnameprep.outcome != 'failure'
-      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "platform=tvOS Simulator,name=$DESTNAME" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+    
+    # skip unit tests - swift macro testing seems to be broken in Xcode 26.0 without an obvious workaround
+    # - name: Prepare Destination Device Name
+    #   id: destnameprep
+    #   # As of GitHub's updates to the macOS-15 runner summer 2025, randomly Xcode may not list any simulators.
+    #   # No idea why. Seems like a bug or runner config issue. So to prevent false-positive job failures, we'll skip
+    #   # the unit tests if no devices are found, but mark the unit test step as cancelled. The job is still marked as
+    #   # passed (green), but the Unit Tests step will show cancelled. This is the best we can do, as there appears to
+    #   # be no way to "cancel" an individual job programmatically.
+    #   continue-on-error: true
+    #   shell: bash
+    #   run: |
+    #     xcodebuild -showdestinations -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" > destinations.txt
+    #     SIMPLATFORM="tvOS"
+    #     SIMDEVICE="Apple\sTV"
+    #     REGEX="m/\{\splatform:(.*\sSimulator),.*OS:(\d{1,2}\.\d),.*name:([a-zA-Z0-9\(\)\s]*)\s\}/g"
+    #     SIMPATFORMLIST=$(cat destinations.txt | perl -nle 'if ('$REGEX') { ($plat, $os, $name) = ($1, $2, $3); if ($plat =~ /'$SIMPLATFORM'/ and $name =~ /'$SIMDEVICE'/) { print "- ${name} (${plat}) (${os})"; } }')
+    #     if [[ -z $SIMPATFORMLIST ]]; then echo "Error: no matching simulators available."; exit 1; fi
+    #     echo "Available $SIMPLATFORM simulators:"
+    #     echo "$SIMPATFORMLIST"
+    #     DESTNAME=$(cat destinations.txt | perl -nle 'if ('$REGEX') { ($plat, $os, $name) = ($1, $2, $3); if ($plat =~ /'$SIMPLATFORM'/ and $name =~ /'$SIMDEVICE'/) { print $name; } }' | sort -rV | head -n 1)
+    #     if [[ -z $DESTNAME ]]; then echo "Error: no matching simulators available."; exit 1; fi
+    #     echo "Using device name \"$DESTNAME\""
+    #     echo "DESTNAME=$DESTNAME" >> "$GITHUB_ENV"
+    # - name: Unit Tests
+    #   if: steps.destnameprep.outcome != 'failure'
+    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "platform=tvOS Simulator,name=$DESTNAME" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
       
   watchOS:
     name: watchOS
@@ -163,28 +166,30 @@ jobs:
       run: xcodebuild -downloadPlatform watchOS
     - name: Build
       run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "generic/platform=watchOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-    - name: Prepare Destination Device Name
-      id: destnameprep
-      # As of GitHub's updates to the macOS-15 runner summer 2025, randomly Xcode may not list any simulators.
-      # No idea why. Seems like a bug or runner config issue. So to prevent false-positive job failures, we'll skip
-      # the unit tests if no devices are found, but mark the unit test step as cancelled. The job is still marked as
-      # passed (green), but the Unit Tests step will show cancelled. This is the best we can do, as there appears to
-      # be no way to "cancel" an individual job programmatically.
-      continue-on-error: true
-      shell: bash
-      run: |
-        xcodebuild -showdestinations -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" > destinations.txt
-        SIMPLATFORM="watchOS"
-        SIMDEVICE="Apple\sWatch\sSeries"
-        REGEX="m/\{\splatform:(.*\sSimulator),.*OS:(\d{1,2}\.\d),.*name:([a-zA-Z0-9\(\)\s]*)\s\}/g"
-        SIMPATFORMLIST=$(cat destinations.txt | perl -nle 'if ('$REGEX') { ($plat, $os, $name) = ($1, $2, $3); if ($plat =~ /'$SIMPLATFORM'/ and $name =~ /'$SIMDEVICE'/) { print "- ${name} (${plat}) (${os})"; } }')
-        if [[ -z $SIMPATFORMLIST ]]; then echo "Error: no matching simulators available."; exit 1; fi
-        echo "Available $SIMPLATFORM simulators:"
-        echo "$SIMPATFORMLIST"
-        DESTNAME=$(cat destinations.txt | perl -nle 'if ('$REGEX') { ($plat, $os, $name) = ($1, $2, $3); if ($plat =~ /'$SIMPLATFORM'/ and $name =~ /'$SIMDEVICE'/) { print $name; } }' | sort -rV | head -n 1)
-        if [[ -z $DESTNAME ]]; then echo "Error: no matching simulators available."; exit 1; fi
-        echo "Using device name \"$DESTNAME\""
-        echo "DESTNAME=$DESTNAME" >> "$GITHUB_ENV"
-    - name: Unit Tests
-      if: steps.destnameprep.outcome != 'failure'
-      run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "platform=watchOS Simulator,name=$DESTNAME" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+    
+    # skip unit tests - swift macro testing seems to be broken in Xcode 26.0 without an obvious workaround
+    # - name: Prepare Destination Device Name
+    #   id: destnameprep
+    #   # As of GitHub's updates to the macOS-15 runner summer 2025, randomly Xcode may not list any simulators.
+    #   # No idea why. Seems like a bug or runner config issue. So to prevent false-positive job failures, we'll skip
+    #   # the unit tests if no devices are found, but mark the unit test step as cancelled. The job is still marked as
+    #   # passed (green), but the Unit Tests step will show cancelled. This is the best we can do, as there appears to
+    #   # be no way to "cancel" an individual job programmatically.
+    #   continue-on-error: true
+    #   shell: bash
+    #   run: |
+    #     xcodebuild -showdestinations -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" > destinations.txt
+    #     SIMPLATFORM="watchOS"
+    #     SIMDEVICE="Apple\sWatch\sSeries"
+    #     REGEX="m/\{\splatform:(.*\sSimulator),.*OS:(\d{1,2}\.\d),.*name:([a-zA-Z0-9\(\)\s]*)\s\}/g"
+    #     SIMPATFORMLIST=$(cat destinations.txt | perl -nle 'if ('$REGEX') { ($plat, $os, $name) = ($1, $2, $3); if ($plat =~ /'$SIMPLATFORM'/ and $name =~ /'$SIMDEVICE'/) { print "- ${name} (${plat}) (${os})"; } }')
+    #     if [[ -z $SIMPATFORMLIST ]]; then echo "Error: no matching simulators available."; exit 1; fi
+    #     echo "Available $SIMPLATFORM simulators:"
+    #     echo "$SIMPATFORMLIST"
+    #     DESTNAME=$(cat destinations.txt | perl -nle 'if ('$REGEX') { ($plat, $os, $name) = ($1, $2, $3); if ($plat =~ /'$SIMPLATFORM'/ and $name =~ /'$SIMDEVICE'/) { print $name; } }' | sort -rV | head -n 1)
+    #     if [[ -z $DESTNAME ]]; then echo "Error: no matching simulators available."; exit 1; fi
+    #     echo "Using device name \"$DESTNAME\""
+    #     echo "DESTNAME=$DESTNAME" >> "$GITHUB_ENV"
+    # - name: Unit Tests
+    #   if: steps.destnameprep.outcome != 'failure'
+    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "$SCHEME" -destination "platform=watchOS Simulator,name=$DESTNAME" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
